### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by poivrot** [juvian/neopets-flash-fix#9]
Hi thanks for putting this together - it's been very useful! 

I had been using this guide and Fiddler/Pale Moon for Windows successfully this past year, but I just started getting a page saying the connection is untrusted for sites that had previously not had any issue. When I investigate "Technical Details", it says the security certificate for the site expired on November 30, 2024. Do you know why this might be happening or what I can do about it?

Thank you again!

**Comment by SpudMonkey7k** [comment]
@poivrot  have you tried removing your fiddler certificate from browser then generating a new certificate in fiddler and readding it to your browser?

**Comment by poivrot** [comment]
This worked - thank you!! Removing the old certificate first before trying to add the new one was the trick!
